sudo: false
dist: trusty

language: python
python:
  - "2.7"

addons:
  apt:
    packages:
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - graphviz
    - libglpk-dev

before_install:
  # gr1c
  - export GR1CVERSION=0.10.2
  - curl -sO http://vehicles.caltech.edu/snapshots/gr1c/gr1c-$GR1CVERSION.tar.gz
  - expr `shasum -a 256 gr1c-$GR1CVERSION.tar.gz|cut -d ' ' -f1`
    = 12762f7fcebca12ce9d36f20ea26d644872a2d6ae616a34d922f23c66bfed1ca
  - tar -xzf gr1c-$GR1CVERSION.tar.gz && cd gr1c-$GR1CVERSION && ./get-deps.sh
  - make -j2 cudd && make -j2 all && make check
  - export PATH=`pwd`:$PATH
  - cd ..
  # miniconda
  - curl -sO https://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh
    && echo 'ada5b7942e519829bc5e8e638d525e009676a7a598cf3dd80f041f6d5e39ddbb  Miniconda2-4.0.5-Linux-x86_64.sh'
    | shasum -a 256 -c -
  - bash Miniconda2-4.0.5-Linux-x86_64.sh -b -p ${HOME}/miniconda
  - source ${HOME}/miniconda/bin/activate root
  - conda update -q -y --all
  - conda install -q -y nomkl
  # python packages
  - conda install -q -y numpy scipy
  - conda info -a
  - pip install --ignore-installed --upgrade pip setuptools
  - pip install nose
  - pip install mock
  # optional python packages
  - pip install gr1py
  # lily
  - ./extern/get-lily.sh
  - which perl
  - perl --version
  - pwd
  - export PERL5LIB=`pwd`/Lily-1.0.2
  - export PATH=`pwd`/Lily-1.0.2:$PATH
  - echo $PATH
  - which lily.pl
  # jtlv
  - ./extern/get-jtlv.sh
  ## install dd.cudd
  - pip install dd
  - pip download --no-dependencies dd>=0.4.0
  - pip uninstall --yes dd
  - tar xzf dd-*.tar.gz
  - cd dd-*/
  - python setup.py install --fetch --cudd
  - cd ..

install:
  - python setup.py sdist
  - pip install dist/tulip-*.tar.gz

before_script:
  - pip install gitpython
  - dot -V

script:
  - ./run_tests.py --outofsource base
  - pip install matplotlib
  - ./run_tests.py --outofsource --fast hybrid
  # install cvxopt.glpk
  - export CVXOPT_BUILD_GLPK=1
  - pip install cvxopt==1.1.7
  - python -c "import cvxopt.glpk"
  # slow hybrid tests
  - ./run_tests.py --outofsource full

notifications:
  email: false
